### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by KevinBjarnemark** [KevinBjarnemark/My-First-Agile-Project#10]
As a **role** I can **send SMS message to remind participants 60 minutes before the run time.** so that **I don't forget about a running event**

### Acceptance Criteria

- User should be able to activate/deactivate SMS reminders for running events.
- An integrated SMS service should automatically send out reminders following a customized template based on running events.
- The service should automatically be inactivated if an event gets canceled.

### Tasks 

- [ ] Include SMS enabling feature in the sign-up process and on the user settings page.
- [ ] Integrate an SMS service that allows messages to be sent in bulk.
- [ ] Sync the integrated SMS handling in harmony with the database in terms of user settings, canceled events, etc.
