### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by KevinBjarnemark** [KevinBjarnemark/My-First-Agile-Project#5]
As a **runner** I can **get quality time with my running friends** so that **I can see who else is running on a particular date**

### Acceptance Criteria

- There should be an option to sign up for a running event on the main page.
- The runners who sign up should have the option to show their name on a particular running date.
- Runners should be able to revert their sign-up.

### Tasks 

- [ ] Design a calendar that highlights the 'running days'.
- [ ] Integrate a booking system that registers the runners in a database.
- [ ] Place the runners on the correct dates.
- [ ] Integrate a system to remove runners from the database.
- [ ] Deploy the calendar system to the main page.
