### ISSUE TITLE
USER STORY: Running competitions

### ISSUE THREAD

**Issue by KevinBjarnemark** [KevinBjarnemark/My-First-Agile-Project#6]
As a **runner** I can **participate in local running competitions** so that **I can find friends nearby to compete with**

### Acceptance Criteria

- There should be running competitions separate from the regular running events listed on the main page.
- The competitions should be clickable for more information.
- It should be possible to edit the competition list.
- It should be possible to sign up for a competition.
- It should be possible to add results from the competitions that have taken place.

### Tasks 

- [ ] Develop a template that administrators can use to publish competition events.
- [ ] Develop an editing system that lets the administrators edit and delete selected events.
- [ ] Store the signed-up users in a database. 
- [ ] Display all runners in a ready-to-print table per event.
- [ ] Develop a system that lets administrators attach the results to an event.
- [ ] Sort the competition events in chronological order.
